### ISSUE TITLE
Axis labels are confusing

### ISSUE THREAD

**Issue by c-meek** [amirziai/cse6242-project#15]
What are "principal component 1" and "principal component 2" in the axis labels? Can we label these in a more user-friendly way?

**Comment by jsaun** [comment]
I don't think we can actually, we could choose to not label them at all however. 
When we represent documents as an N-dimension vector, each dimension means something typically a word, but to be able to graph it, we reduce it down to 2 dimensions, this process tries to preserve how close vectors are to each other, but the X and Y values don't really mean anything anymore.

**Comment by c-meek** [comment]
Ah, I see. That makes sense. Maybe the solution is to remove the axes then?
Improve our ink/data ratio?

**Comment by c-meek** [comment]
Remove the labels, not axes**

**Comment by c-meek** [comment]
If the units don't mean anything, we might consider removing axes altogether. @jsaun @amirziai @cpu-meltdown @ncshields thoughts? I'll get this in on the issue-15 branch, let's discuss before I submit a PR.

![image](https://user-images.githubusercontent.com/3596743/48666400-e93d9300-ea75-11e8-849b-3cd5fe86e1e5.png)

**Comment by jsaun** [comment]
That's fine with me
